package com.draganstojanov.myworld_compose.model

import kotlinx.serialization.SerialName

data class Country(

    val region: String? = null,
    val subregion: String? = null,
    val continents: List<String?>? = null,

    val name: Name? = null,
    val altSpellings: List<String?>? = null,

    val cca2: String? = null,
    val cca3: String? = null,
    val ccn3: String? = null,
    val flag: String? = null,

    val car: Car? = null,
    val idd: Idd? = null,
    val tld: List<String?>? = null,

    val fifa: String? = null,
    val cioc: String? = null,

    val flags: Flags? = null,
    val coatOfArms: CoatOfArms? = null,

    val maps: Maps? = null,
    val latlng: List<Any?>? = null,

    val capital: List<String?>? = null,
    val capitalInfo: CapitalInfo? = null,
    val area: Long? = null,
    val population: Int? = null,

    val borders: List<String?>? = null,
    val independent: Boolean? = null,
    val unMember: Boolean? = null,
    val landlocked: Boolean? = null,

    val gini: Gini? = null,
    val currencies: Currencies? = null,
    val languages: Languages? = null,
    val timezones: List<String?>? = null,

    )

data class Flags(
    val svg: String? = null,
    val png: String? = null,
    val alt: String? = null
)

data class Maps(
    val openStreetMaps: String? = null,
    val googleMaps: String? = null
)

data class CapitalInfo(
    val latlng: List<Any?>? = null
)

data class CoatOfArms(
    val svg: String? = null,
    val png: String? = null
)

data class Currency(
    val symbol: String? = null,
    val name: String? = null
)

data class Currencies(
    val XOF: Currency? = null,
    val NZD: Currency? = null,
    val OMR: Currency? = null,
    val DKK: Currency? = null,
    val KRW: Currency? = null,
    val TWD: Currency? = null,
    val EUR: Currency? = null,
    val USD: Currency? = null,
    val AUD: Currency? = null,
    val SCR: Currency? = null,
    val BSD: Currency? = null,
    val MWK: Currency? = null,
    val XCD: Currency? = null,
    val LSL: Currency? = null,
    val ZAR: Currency? = null,
    val KYD: Currency? = null,
    val AOA: Currency? = null,
    val SRD: Currency? = null,
    val LKR: Currency? = null,
    val UZS: Currency? = null,
    val SDG: Currency? = null,
    val KID: Currency? = null,
    val CHF: Currency? = null,
    val BIF: Currency? = null,
    val TND: Currency? = null,
    val THB: Currency? = null,
    val IQD: Currency? = null,
    val TOP: Currency? = null,
    val HUF: Currency? = null,
    val ANG: Currency? = null,
    val ILS: Currency? = null,
    val JOD: Currency? = null,
    val EGP: Currency? = null,
    val VES: Currency? = null,
    val LAK: Currency? = null,
    val AWG: Currency? = null,
    val CNY: Currency? = null,
    val GYD: Currency? = null,
    val BRL: Currency? = null,
    val JPY: Currency? = null,
    val VND: Currency? = null,
    val HKD: Currency? = null,
    val XPF: Currency? = null,
    val KGS: Currency? = null,
    val GBP: Currency? = null,
    val IMP: Currency? = null,
    val ZMW: Currency? = null,
    val FOK: Currency? = null,
    val PYG: Currency? = null,
    val NPR: Currency? = null,
    val UGX: Currency? = null,
    val WST: Currency? = null,
    val BMD: Currency? = null,
    val MYR: Currency? = null,
    val COP: Currency? = null,
    val SAR: Currency? = null,
    val BZD: Currency? = null,
    val TZS: Currency? = null,
    val ZWL: Currency? = null,
    val ERN: Currency? = null,
    val KWD: Currency? = null,
    val GHS: Currency? = null,
    val SGD: Currency? = null,
    val BND: Currency? = null,
    val TMT: Currency? = null,
    val FKP: Currency? = null,
    val KMF: Currency? = null,
    val JMD: Currency? = null,
    val XAF: Currency? = null,
    val NOK: Currency? = null,
    val PKR: Currency? = null,
    val CZK: Currency? = null,
    val AED: Currency? = null,
    val GGP: Currency? = null,
    val SSP: Currency? = null,
    val ALL: Currency? = null,
    val SHP: Currency? = null,
    val AMD: Currency? = null,
    val LRD: Currency? = null,
    val BYN: Currency? = null,
    val IDR: Currency? = null,
    val DOP: Currency? = null,
    val BOB: Currency? = null,
    val MDL: Currency? = null,
    val NAD: Currency? = null,
    val LYD: Currency? = null,
    val ETB: Currency? = null,
    val MNT: Currency? = null,
    val RSD: Currency? = null,
    val GEL: Currency? = null,
    val BHD: Currency? = null,
    val GNF: Currency? = null,
    val SBD: Currency? = null,
    val KPW: Currency? = null,
    val FJD: Currency? = null,
    val ISK: Currency? = null,
    val MXN: Currency? = null,
    val GIP: Currency? = null,
    val SYP: Currency? = null,
    val HTG: Currency? = null,
    val DJF: Currency? = null,
    val SZL: Currency? = null,
    val PEN: Currency? = null,
    val VUV: Currency? = null,
    val PLN: Currency? = null,
    val IRR: Currency? = null,
    val UAH: Currency? = null,
    val MGA: Currency? = null,
    val MAD: Currency? = null,
    val SEK: Currency? = null,
    val SOS: Currency? = null,
    val YER: Currency? = null,
    val QAR: Currency? = null,
    val MRU: Currency? = null,
    val CAD: Currency? = null,
    val BWP: Currency? = null,
    val AFN: Currency? = null,
    val MKD: Currency? = null,
    val UYU: Currency? = null,
    val BGN: Currency? = null,
    val CVE: Currency? = null,
    val CLP: Currency? = null,
    val RON: Currency? = null,
    val AZN: Currency? = null,
    val TJS: Currency? = null,
    val ARS: Currency? = null,
    val KZT: Currency? = null,
    val PHP: Currency? = null,
    val KES: Currency? = null,
    val LBP: Currency? = null,
    val MMK: Currency? = null,
    val GMD: Currency? = null,
    val TTD: Currency? = null,
    val MOP: Currency? = null,
    val HNL: Currency? = null,
    val PGK: Currency? = null,
    val CKD: Currency? = null,
    val CRC: Currency? = null,
    val JEP: Currency? = null,
    val CUC: Currency? = null,
    val CUP: Currency? = null,
    val RUB: Currency? = null,
    val NGN: Currency? = null,
    val MZN: Currency? = null,
    val TRY: Currency? = null,
    val RWF: Currency? = null,
    val DZD: Currency? = null,
    val BBD: Currency? = null,
    val SLL: Currency? = null,
    val NIO: Currency? = null,
    val PAB: Currency? = null,
    val CDF: Currency? = null,
    val MUR: Currency? = null,
    val KHR: Currency? = null,
    val INR: Currency? = null,
    val TVD: Currency? = null,
    val STN: Currency? = null,
    val BTN: Currency? = null,
    val BDT: Currency? = null,
    val MVR: Currency? = null,
    val BAM: Currency? = null,
    val GTQ: Currency? = null
)


data class Languages(
    val fra: String? = null,
    val eng: String? = null,
    val ara: String? = null,
    val dan: String? = null,
    val kor: String? = null,
    val zho: String? = null,
    val deu: String? = null,
    val nld: String? = null,
    val crs: String? = null,
    val por: String? = null,
    val pov: String? = null,
    val nya: String? = null,
    val sot: String? = null,
    val tam: String? = null,
    val sin: String? = null,
    val rus: String? = null,
    val uzb: String? = null,
    val gil: String? = null,
    val swe: String? = null,
    val ita: String? = null,
    val gsw: String? = null,
    val roh: String? = null,
    val run: String? = null,
    val tha: String? = null,
    val arc: String? = null,
    val ckb: String? = null,
    val ton: String? = null,
    val hun: String? = null,
    val spa: String? = null,
    val lao: String? = null,
    val pap: String? = null,
    val cha: String? = null,
    val slk: String? = null,
    val cnr: String? = null,
    val pih: String? = null,
    val jpn: String? = null,
    val fin: String? = null,
    val gle: String? = null,
    val vie: String? = null,
    val tet: String? = null,
    val cal: String? = null,
    val kir: String? = null,
    val glv: String? = null,
    val smo: String? = null,
    val tkl: String? = null,
    val fao: String? = null,
    val grn: String? = null,
    val nep: String? = null,
    val swa: String? = null,
    val de: String? = null,
    val msa: String? = null,
    val mri: String? = null,
    val nzs: String? = null,
    val bjz: String? = null,
    val est: String? = null,
    val sna: String? = null,
    val ndc: String? = null,
    val khi: String? = null,
    val nde: String? = null,
    val tsn: String? = null,
    val toi: String? = null,
    val tso: String? = null,
    val kck: String? = null,
    val zib: String? = null,
    val bwg: String? = null,
    val ven: String? = null,
    val xho: String? = null,
    val tir: String? = null,
    val tuk: String? = null,
    val zdj: String? = null,
    val jam: String? = null,
    val nor: String? = null,
    val lat: String? = null,
    val urd: String? = null,
    val ces: String? = null,
    val nfr: String? = null,
    val cat: String? = null,
    val sqi: String? = null,
    val hye: String? = null,
    val zul: String? = null,
    val ssw: String? = null,
    val nbl: String? = null,
    val nso: String? = null,
    val afr: String? = null,
    val mlt: String? = null,
    val lin: String? = null,
    val kon: String? = null,
    val bel: String? = null,
    val ind: String? = null,
    val que: String? = null,
    val aym: String? = null,
    val ron: String? = null,
    val kwn: String? = null,
    val her: String? = null,
    val loz: String? = null,
    val ndo: String? = null,
    val hgm: String? = null,
    val amh: String? = null,
    val kal: String? = null,
    val mon: String? = null,
    val sag: String? = null,
    val srp: String? = null,
    val kat: String? = null,
    val lit: String? = null,
    val hif: String? = null,
    val fij: String? = null,
    val isl: String? = null,
    val hat: String? = null,
    val ltz: String? = null,
    val pau: String? = null,
    val bis: String? = null,
    val pol: String? = null,
    val fas: String? = null,
    val ukr: String? = null,
    val mlg: String? = null,
    val ber: String? = null,
    val som: String? = null,
    val prs: String? = null,
    val pus: String? = null,
    val mkd: String? = null,
    val bul: String? = null,
    val tur: String? = null,
    val ell: String? = null,
    val aze: String? = null,
    val tgk: String? = null,
    val kaz: String? = null,
    val fil: String? = null,
    val hrv: String? = null,
    val mya: String? = null,
    val hmo: String? = null,
    val tpi: String? = null,
    val slv: String? = null,
    val niu: String? = null,
    val rar: String? = null,
    val nrf: String? = null,
    val mah: String? = null,
    val kin: String? = null,
    val mey: String? = null,
    val heb: String? = null,
    val lua: String? = null,
    val mfe: String? = null,
    val khm: String? = null,
    val hin: String? = null,
    val tvl: String? = null,
    val nob: String? = null,
    val nno: String? = null,
    val smi: String? = null,
    val nau: String? = null,
    val dzo: String? = null,
    val ben: String? = null,
    val lav: String? = null,
    val div: String? = null,
    val bos: String? = null
)

data class Car(
    val side: String? = null,
    val signs: List<String?>? = null
)

data class Idd(
    val suffixes: List<String?>? = null,
    val root: String? = null
)

data class Name(
    val nativeName: NativeName? = null,
    val common: String? = null,
    val official: String? = null
)

data class Native(
    val common: String? = null,
    val official: String? = null
)

data class NativeName(
    val fra: Native? = null,
    val eng: Native? = null,
    val ara: Native? = null,
    val dan: Native? = null,
    val kor: Native? = null,
    val zho: Native? = null,
    val deu: Native? = null,
    val nld: Native? = null,
    val crs: Native? = null,
    val por: Native? = null,
    val pov: Native? = null,
    val nya: Native? = null,
    val sot: Native? = null,
    val tam: Native? = null,
    val sin: Native? = null,
    val rus: Native? = null,
    val uzb: Native? = null,
    val gil: Native? = null,
    val swe: Native? = null,
    val ita: Native? = null,
    val gsw: Native? = null,
    val roh: Native? = null,
    val run: Native? = null,
    val tha: Native? = null,
    val arc: Native? = null,
    val ckb: Native? = null,
    val ton: Native? = null,
    val hun: Native? = null,
    val spa: Native? = null,
    val lao: Native? = null,
    val pap: Native? = null,
    val cha: Native? = null,
    val slk: Native? = null,
    val cnr: Native? = null,
    val pih: Native? = null,
    val jpn: Native? = null,
    val fin: Native? = null,
    val gle: Native? = null,
    val vie: Native? = null,
    val tet: Native? = null,
    val cal: Native? = null,
    val kir: Native? = null,
    val glv: Native? = null,
    val smo: Native? = null,
    val tkl: Native? = null,
    val fao: Native? = null,
    val grn: Native? = null,
    val nep: Native? = null,
    val swa: Native? = null,
    val bar: Native? = null,
    val msa: Native? = null,
    val mri: Native? = null,
    val nzs: Native? = null,
    val bjz: Native? = null,
    val est: Native? = null,
    val sna: Native? = null,
    val ndc: Native? = null,
    val khi: Native? = null,
    val nde: Native? = null,
    val tsn: Native? = null,
    val toi: Native? = null,
    val tso: Native? = null,
    val kck: Native? = null,
    val zib: Native? = null,
    val bwg: Native? = null,
    val ven: Native? = null,
    val xho: Native? = null,
    val tir: Native? = null,
    val tuk: Native? = null,
    val zdj: Native? = null,
    val jam: Native? = null,
    val nor: Native? = null,
    val lat: Native? = null,
    val urd: Native? = null,
    val ces: Native? = null,
    val nfr: Native? = null,
    val cat: Native? = null,
    val sqi: Native? = null,
    val hye: Native? = null,
    val zul: Native? = null,
    val ssw: Native? = null,
    val nbl: Native? = null,
    val nso: Native? = null,
    val afr: Native? = null,
    val mlt: Native? = null,
    val lin: Native? = null,
    val kon: Native? = null,
    val bel: Native? = null,
    val ind: Native? = null,
    val que: Native? = null,
    val aym: Native? = null,
    val ron: Native? = null,
    val kwn: Native? = null,
    val her: Native? = null,
    val loz: Native? = null,
    val ndo: Native? = null,
    val hgm: Native? = null,
    val amh: Native? = null,
    val kal: Native? = null,
    val mon: Native? = null,
    val sag: Native? = null,
    val srp: Native? = null,
    val kat: Native? = null,
    val lit: Native? = null,
    val hif: Native? = null,
    val fij: Native? = null,
    val isl: Native? = null,
    val hat: Native? = null,
    val ltz: Native? = null,
    val pau: Native? = null,
    val bis: Native? = null,
    val pol: Native? = null,
    val fas: Native? = null,
    val ukr: Native? = null,
    val mlg: Native? = null,
    val ber: Native? = null,
    val som: Native? = null,
    val prs: Native? = null,
    val pus: Native? = null,
    val mkd: Native? = null,
    val bul: Native? = null,
    val tur: Native? = null,
    val ell: Native? = null,
    val aze: Native? = null,
    val tgk: Native? = null,
    val kaz: Native? = null,
    val fil: Native? = null,
    val hrv: Native? = null,
    val mya: Native? = null,
    val hmo: Native? = null,
    val tpi: Native? = null,
    val slv: Native? = null,
    val niu: Native? = null,
    val rar: Native? = null,
    val nrf: Native? = null,
    val mah: Native? = null,
    val kin: Native? = null,
    val mey: Native? = null,
    val heb: Native? = null,
    val lua: Native? = null,
    val mfe: Native? = null,
    val khm: Native? = null,
    val hin: Native? = null,
    val tvl: Native? = null,
    val nob: Native? = null,
    val nno: Native? = null,
    val smi: Native? = null,
    val nau: Native? = null,
    val dzo: Native? = null,
    val ben: Native? = null,
    val lav: Native? = null,
    val div: Native? = null,
    val bos: Native? = null
)

data class Gini(
    @SerialName("2011")
    val gini2011: Double? = null,

    @SerialName("2018")
    val gini2018: Double? = null,

    @SerialName("2016")
    val gini2016: Double? = null,

    @SerialName("2013")
    val gini2013: Double? = null,

    @SerialName("2010")
    val gini2010: Double? = null,

    @SerialName("2017")
    val gini2017: Double? = null,

    @SerialName("2015")
    val gini2015: Double? = null,

    @SerialName("1999")
    val gini1999: Double? = null,

    @SerialName("2014")
    val gini2014: Double? = null,

    @SerialName("2003")
    val gini2003: Double? = null,

    @SerialName("2006")
    val gini2006: Double? = null,

    @SerialName("2019")
    val gini2019: Double? = null,

    @SerialName("2012")
    val gini2012: Double? = null,

    @SerialName("1998")
    val gini1998: Double? = null,

    @SerialName("2004")
    val gini2004: Double? = null,

    @SerialName("2009")
    val gini2009: Double? = null,

    @SerialName("2018")
    val gini2008: Double? = null,

    @SerialName("2005")
    val gini2005: Double? = null,

    @SerialName("1992")
    val gini1992: Double? = null
)